# .github/workflows/algolia-sync.yml

name: Sync Products to Algolia

on:
  push:
    branches:
      - main

jobs:
  sync-algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Algolia client
        run: npm install algoliasearch

      - name: Run Algolia sync script
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: node ./upload-to-algolia.js
