# .github/workflows/azure-webapps-node.yml

# This is a simplified workflow for deploying a STATIC website to Azure Web App.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # IMPORTANT: set this to your application's name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Deploys the files to Azure Web App
    # This action knows how to deploy static content directly.
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.' # Deploy the entire repository root
